/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGUI;


import escuelanew.Curso;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class PrincipalGui extends javax.swing.JFrame {
    ArrayList<Curso>cursos = new ArrayList<>();
    /**
     * Creates new form PrincipalGui
     */
    public PrincipalGui() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        eliminarAlumnos = new javax.swing.JButton();
        agregarAlumnos = new javax.swing.JButton();
        bucarCursoProfesor = new javax.swing.JButton();
        buscarAlumno = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        eliminarCursos = new javax.swing.JButton();
        agregarCursos = new javax.swing.JButton();
        buscarCursos = new javax.swing.JButton();
        mostrarCursos = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 31, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\descarga (3).jpeg")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 34, -1, 378));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        jPanel3.setBackground(new java.awt.Color(58, 109, 140));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Gestión de Cursos");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 104, 37, 113);
        jPanel3.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 5, 460, 80));

        jPanel4.setBackground(new java.awt.Color(106, 154, 176));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestión de Alumnos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 201;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 47, 11, 65);
        jPanel4.add(jLabel2, gridBagConstraints);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 440, 50));

        salir.setBackground(new java.awt.Color(255, 102, 102));
        salir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 430, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        eliminarAlumnos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        eliminarAlumnos.setText("Eliminar Alumno");
        eliminarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAlumnosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 33, 0, 0);
        jPanel5.add(eliminarAlumnos, gridBagConstraints);

        agregarAlumnos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        agregarAlumnos.setText("Agregar Alumno");
        agregarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlumnosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 0, 0);
        jPanel5.add(agregarAlumnos, gridBagConstraints);

        bucarCursoProfesor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bucarCursoProfesor.setText("Buscar Cursos Dados");
        bucarCursoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucarCursoProfesorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 18, 17, 36);
        jPanel5.add(bucarCursoProfesor, gridBagConstraints);

        buscarAlumno.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buscarAlumno.setText("Buscar Alumno");
        buscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlumnoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 48, 17, 0);
        jPanel5.add(buscarAlumno, gridBagConstraints);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 430, -1));

        jPanel6.setBackground(new java.awt.Color(106, 154, 176));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestión de Alumnos");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 328, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 430, 60));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        eliminarCursos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        eliminarCursos.setText("Eliminar Curso");
        eliminarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCursosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 47, 0, 59);
        jPanel7.add(eliminarCursos, gridBagConstraints);

        agregarCursos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        agregarCursos.setText("Agregar Curso");
        agregarCursos.setToolTipText("Haz click para agregar un curso.");
        agregarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCursosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 48, 0, 0);
        jPanel7.add(agregarCursos, gridBagConstraints);

        buscarCursos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buscarCursos.setText("Buscar Cursos");
        buscarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCursosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 47, 13, 59);
        jPanel7.add(buscarCursos, gridBagConstraints);

        mostrarCursos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        mostrarCursos.setText("Mostrar Cursos");
        mostrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCursosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 48, 13, 0);
        jPanel7.add(mostrarCursos, gridBagConstraints);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 430, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void agregarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlumnosActionPerformed
         Curso cursoActual = new Curso();
         cursoActual.addEstudiantesCurso(cursos);
    }//GEN-LAST:event_agregarAlumnosActionPerformed

    private void bucarCursoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarCursoProfesorActionPerformed
         Curso cursoActual = new Curso();
        cursoActual.buscarCursosProfesor(cursos);
    }//GEN-LAST:event_bucarCursoProfesorActionPerformed

    private void eliminarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCursosActionPerformed
        Curso cursoActual = new Curso();
        cursoActual.eliminarCurso(cursos);
    }//GEN-LAST:event_eliminarCursosActionPerformed

    private void agregarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCursosActionPerformed
        Curso cursoActual = new Curso();
       cursoActual.addCurso(cursos);
    }//GEN-LAST:event_agregarCursosActionPerformed

    private void mostrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCursosActionPerformed
        Curso cursoActual = new Curso();
        cursoActual.mostrarCurso(cursos);
    }//GEN-LAST:event_mostrarCursosActionPerformed

    private void buscarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCursosActionPerformed
        Curso cursoActual = new Curso();
        cursoActual.buscarCurso(cursos);
    }//GEN-LAST:event_buscarCursosActionPerformed

    private void eliminarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAlumnosActionPerformed
         Curso cursoActual = new Curso();
        cursoActual.eliminarAlumnos(cursos);
    }//GEN-LAST:event_eliminarAlumnosActionPerformed

    private void buscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlumnoActionPerformed
        Curso cursoActual = new Curso();
        cursoActual.buscarAlumno(cursos);
    }//GEN-LAST:event_buscarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAlumnos;
    private javax.swing.JButton agregarCursos;
    private javax.swing.JButton bucarCursoProfesor;
    private javax.swing.JButton buscarAlumno;
    private javax.swing.JButton buscarCursos;
    private javax.swing.JButton eliminarAlumnos;
    private javax.swing.JButton eliminarCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mostrarCursos;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
